//conected DB
spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-dark-scene-aloa16p4-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xEsFv63eAlTw
spring.datasource.driver-class-name=org.postgresql.Driver
// request Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
//show sql reaquest
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
//for file uploud
spring.servlet.multipart.max-file-size=5MB

spring.servlet.multipart.max-request-size=10MB
//Telegram_Bot_Config
telegram.bot.username =LNU_Tracker_bot
telegram.bot.token =8643708733:AAH7NxkjX6Bt9GPRJ970glXuciJJAlDy5f8
